apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: new-web
  template:
    metadata:
      labels:
        app: new-web
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: new-web
          image: mahmoudghanem/new-web:e64cc7a33078d9321758458dd3e86adfdf87b76
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/newwebdb
            - name: SPRING_DATASOURCE_USERNAME
              value: newweb
            - name: SPRING_DATASOURCE_PASSWORD
              value: newwebpass
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"